services:
  frontend:
    build: ./frontend
    container_name: express-learning-frontend
    ports:
      - "3001:3000" # ホストの3001番をコンテナの3000番に繋ぐ
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - WATCHPACK_POLLING=true # Windows環境でのホットリロードを安定させる

  app:
    build: ./backend
    container_name: express-learning-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: express-learning-database
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
